### ISSUE TITLE
TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by matoni555** [robwierzbowski/grunt-pixrem#8]
I'm using grunt-pixrem, but on current project I get this error:

```javascript
[TypeError: Arguments to path.resolve must be strings]
Warning: Pixrem failed.
Arguments to path.resolve must be strings
 Use --force to continue.
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at Object.exports.relative (path.js:240:18)
    at MapGenerator.relative (C:\node_modules\grunt-pixrem\node_modules\pixrem\node_modules\postcss\lib\map-generator.js:165:19)
    at MapGenerator.applyPrevMap (C:\node_modules\grunt-pixrem\node_modules\pixrem\node_modules\postcss\lib\map-generator.js:117:21)
    at MapGenerator.generateMap (C:\node_modules\grunt-pixrem\node_modules\pixrem\node_modules\postcss\lib\map-generator.js:153:12)
    at MapGenerator.getResult (C:\node_modules\grunt-pixrem\node_modules\pixrem\node_modules\postcss\lib\map-generator.js:230:21)
    at Root.toResult (C:\node_modules\grunt-pixrem\node_modules\pixrem\node_modules\postcss\lib\root.js:48:18)
    at PostCSS.process (C:\node_modules\grunt-pixrem\node_modules\pixrem\node_modules\postcss\lib\postcss.js:41:21)
    at pixrem (C:\node_modules\grunt-pixrem\node_modules\pixrem\lib\pixrem.js:60:24)
    at C:\node_modules\grunt-pixrem\tasks\pixrem.js:51:18
```

I have Grunt v0.4.5 and grunt-pixrem v0.1.2.
My configuration of pixrem task:

```javascript
pixrem: {
	options: {
		rootvalue: '16px',
	},
	style: {
		src: 'dist/style.css',
		dest: 'dist/style.css'
	},
	editor: {
		src: 'dist/editor-style.css',
		dest: 'dist/editor-style.css'
	}
},
```

What am I doing wrong?

Thank you
Thomas

**Comment by jzatt** [comment]
I'm having this same issue as well, with the same configuration.
Did you manage to find a way around it @matoni555 ?

**Comment by matoni555** [comment]
@jzatt: Problem is with outdated version of postcss. I fixed problem with using of new version of postcss. I will put on Github in free time.

**Comment by jzatt** [comment]
Got it working now by changing version in package.json from ``"grunt-pixrem": "^0.1.2"`` into ``"^0.1.0"``
